
#include "compiler.hpp"

using namespace Parser;

namespace Compiler {

    const char* SizeString[] {
        "byte",
        "word",
        "dword",
        "qword"
    };

    Register registers[] {
        Register{
            Reg::NUL,
            {
                "NULL",
                "NULL",
                "NULL",
                "NULL",
            },
            {ValueType::EMPTY,0,true}
        },
        Register{
            Reg::RAX,
            {
                "al",
                "ax",
                "eax",
                "rax"
            },
            {}
        },
        Register{
            Reg::RBX,
            {
                "bl",
                "bx",
                "ebx",
                "rbx"
            },
            {}
        },
        Register{
            Reg::RCX,
            {
                "cl",
                "cx",
                "ecx",
                "rcx"
            },
            {}
        },
        Register{
            Reg::RDX,
            {
                "dl",
                "dx",
                "edx",
                "rdx"
            },
            {}
        },
        Register{
            Reg::R8,
            {
                "r8b",
                "r8w",
                "r8d",
                "r8"
            },
            {}
        },
        Register{
            Reg::R9,
            {
                "r9b",
                "r9w",
                "r9d",
                "r9"
            },
            {}
        },
        Register{
            Reg::R10,
            {
                "r10b",
                "r10w",
                "r10d",
                "r10"
            },
            {}
        },
        Register{
            Reg::R11,
            {
                "r11b",
                "r11w",
                "r11d",
                "r11"
            },
            {}
        },
        Register{
            Reg::R12,
            {
                "r12b",
                "r12w",
                "r12d",
                "r12"
            },
            {}
        },
        Register{
            Reg::R13,
            {
                "r13b",
                "r13w",
                "r13d",
                "r13"
            },
            {}
        },
        Register{
            Reg::R14,
            {
                "r14b",
                "r14w",
                "r14d",
                "r14"
            },
            {}
        },
        Register{
            Reg::R15,
            {
                "r15b",
                "r15w",
                "r15d",
                "r15"
            },
            {}
        },
        Register{
            Reg::RSI,
            {
                "sil",
                "si",
                "esi",
                "rsi"
            },
            {}
        },
        Register{
            Reg::RDI,
            {
                "dil",
                "di",
                "edi",
                "rdi"
            },
            {}
        },
        Register{
            Reg::RBP,
            {
                "bpl",
                "bp",
                "ebp",
                "rbp"
            },
            {}
        },
        Register{
            Reg::RSP,
            {
                "spl",
                "sp",
                "esp",
                "rsp"
            },
            {}
        },
                Register{
            Reg::XMM0,
            {
                "XMM0",
                "YMM0",
                "ZMM0",
                "XMM0-NULL"
            },
            {}
        },
        Register{
            Reg::XMM1,
            {
                "XMM1",
                "YMM1",
                "ZMM1",
                "XMM1-NULL"
            },
            {}
        },
        Register{
            Reg::XMM2,
            {
                "XMM2",
                "YMM2",
                "ZMM2",
                "XMM2-NULL"
            },
            {}
        },
        Register{
            Reg::XMM3,
            {
                "XMM3",
                "YMM3",
                "ZMM3",
                "XMM3-NULL"
            },
            {}
        },
        Register{
            Reg::XMM4,
            {
                "XMM4",
                "YMM4",
                "ZMM4",
                "XMM4-NULL"
            },
            {}
        },
        Register{
            Reg::XMM5,
            {
                "XMM5",
                "YMM5",
                "ZMM5",
                "XMM5-NULL"
            },
            {}
        },
        Register{
            Reg::XMM6,
            {
                "XMM6",
                "YMM6",
                "ZMM6",
                "XMM6-NULL"
            },
            {}
        },
        Register{
            Reg::XMM7,
            {
                "XMM7",
                "YMM7",
                "ZMM7",
                "XMM7-NULL"
            },
            {}
        },
        Register{
            Reg::XMM8,
            {
                "XMM8",
                "YMM8",
                "ZMM8",
                "XMM8-NULL"
            },
            {}
        },
        Register{
            Reg::XMM9,
            {
                "XMM9",
                "YMM9",
                "ZMM9",
                "XMM9-NULL"
            },
            {}
        },
        Register{
            Reg::XMM10,
            {
                "XMM10",
                "YMM10",
                "ZMM10",
                "XMM10-NULL"
            },
            {}
        },
        Register{
            Reg::XMM11,
            {
                "XMM11",
                "YMM11",
                "ZMM11",
                "XMM11-NULL"
            },
            {}
        },
        Register{
            Reg::XMM12,
            {
                "XMM12",
                "YMM12",
                "ZMM12",
                "XMM12-NULL"
            },
            {}
        },
        Register{
            Reg::XMM13,
            {
                "XMM13",
                "YMM13",
                "ZMM13",
                "XMM13-NULL"
            },
            {}
        },
        Register{
            Reg::XMM14,
            {
                "XMM14",
                "YMM14",
                "ZMM14",
                "XMM14-NULL"
            },
            {}
        },
        Register{
            Reg::XMM15,
            {
                "XMM15",
                "YMM15",
                "ZMM15",
                "XMM15-NULL"
            },
            {}
        },
    };

};
