
#include "compiler.hpp"

using namespace Parser;

namespace Compiler {

    const char* SizeString[] {
        "byte",
        "word",
        "dword",
        "qword"
    };

    Register registers[] {
        Register{
            Reg::NUL,
            {
                "NULL",
                "NULL",
                "NULL",
                "NULL",
            },
            {ValueType::EMPTY,0,true}
        },
        Register{
            Reg::RAX,
            {
                "al",
                "ax",
                "eax",
                "rax"
            },
            {}
        },
        Register{
            Reg::RBX,
            {
                "bl",
                "bx",
                "ebx",
                "rbx"
            },
            {}
        },
        Register{
            Reg::RCX,
            {
                "cl",
                "cx",
                "ecx",
                "rcx"
            },
            {}
        },
        Register{
            Reg::RDX,
            {
                "dl",
                "dx",
                "edx",
                "rdx"
            },
            {}
        },
        Register{
            Reg::R8,
            {
                "r8b",
                "r8w",
                "r8d",
                "r8"
            },
            {}
        },
        Register{
            Reg::R9,
            {
                "r9b",
                "r9w",
                "r9d",
                "r9"
            },
            {}
        },
        Register{
            Reg::R10,
            {
                "r10b",
                "r10w",
                "r10d",
                "r10"
            },
            {}
        },
        Register{
            Reg::R11,
            {
                "r11b",
                "r11w",
                "r11d",
                "r11"
            },
            {}
        },
        Register{
            Reg::R12,
            {
                "r12b",
                "r12w",
                "r12d",
                "r12"
            },
            {}
        },
        Register{
            Reg::R13,
            {
                "r13b",
                "r13w",
                "r13d",
                "r13"
            },
            {}
        },
        Register{
            Reg::R14,
            {
                "r14b",
                "r14w",
                "r14d",
                "r14"
            },
            {}
        },
        Register{
            Reg::R15,
            {
                "r15b",
                "r15w",
                "r15d",
                "r15"
            },
            {}
        },
        Register{
            Reg::RSI,
            {
                "sil",
                "si",
                "esi",
                "rsi"
            },
            {}
        },
        Register{
            Reg::RDI,
            {
                "dil",
                "di",
                "edi",
                "rdi"
            },
            {}
        },
        Register{
            Reg::RBP,
            {
                "bpl",
                "bp",
                "ebp",
                "rbp"
            },
            {}
        },
        Register{
            Reg::RSP,
            {
                "spl",
                "sp",
                "esp",
                "rsp"
            },
            {}
        },
    };

};
