
#include "compiler.hpp"

using namespace Parser;

namespace Compiler {

    const char* SizeString[] {
        "byte",
        "word",
        "dword",
        "qword"
    };

    Register registers[] {
        Register{
            Reg::RAX,
            {
                "al",
                "ax",
                "eax",
                "rax"
            }
        },
        Register{
            Reg::RBX,
            {
                "bl",
                "bx",
                "ebx",
                "rbx"
            }
        },
        Register{
            Reg::RCX,
            {
                "cl",
                "cx",
                "ecx",
                "rcx"
            }
        },
        Register{
            Reg::RDX,
            {
                "dl",
                "dx",
                "edx",
                "rdx"
            }
        },
        Register{
            Reg::RDI,
            {
                "dil",
                "di",
                "edi",
                "rdi"
            }
        },
        Register{
            Reg::RSI,
            {
                "sil",
                "si",
                "esi",
                "rsi"
            }
        },
        Register{
            Reg::RBP,
            {
                "bpl",
                "bp",
                "ebp",
                "rbp"
            }
        },
        Register{
            Reg::RSP,
            {
                "spl",
                "sp",
                "esp",
                "rsp"
            }
        },
        Register{
            Reg::R8,
            {
                "R8B",
                "R8W",
                "R8D",
                "R8"
            }
        },
        Register{
            Reg::R9,
            {
                "R9B",
                "R9W",
                "R9D",
                "R9"
            }
        },
        Register{
            Reg::R10,
            {
                "R10B",
                "R10W",
                "R10D",
                "R10"
            }
        },
        Register{
            Reg::R11,
            {
                "R11B",
                "R11W",
                "R11D",
                "R11"
            }
        },
        Register{
            Reg::R12,
            {
                "R12B",
                "R12W",
                "R12D",
                "R12"
            }
        },
        Register{
            Reg::R13,
            {
                "R13B",
                "R13W",
                "R13D",
                "R13"
            }
        },
        Register{
            Reg::R13,
            {
                "R13B",
                "R13W",
                "R13D",
                "R13"
            }
        },
        Register{
            Reg::R14,
            {
                "R14B",
                "R14W",
                "R14D",
                "R14"
            }
        },
        Register{
            Reg::R15,
            {
                "R15B",
                "R15W",
                "R15D",
                "R15"
            }
        },
    };

};
