#!/bin/bash

clear

echo compiling and running $1...

part=$(echo $1 | cut -d. -f1)
echo $part

./../bin/output.exe $1 && \
    nasm -f elf64 ${part}.asm -o bin/${part}.o && \
    cd .. && \
    nasm -f elf64 src/builtins/builtins.asm -o examples/bin/builtins.o && \
    cd examples && \
    gcc -no-pie -nostdlib bin/${part}.o bin/builtins.o -o bin/${part}.out && \
    ./bin/${part}.out
